# Generated by Django 2.2.7 on 2019-11-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0002_assignment_choice_gradedassignment_question_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='black.Assignment'),
        ),
    ]
